/*Copyright (c) 2017-2018 offline.com All Rights Reserved.
 This software is the confidential and proprietary information of offline.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with offline.com*/
package com.dev_6thjune_web.test_blob1.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class InsertQueryRequest implements Serializable {

    @NotNull
    @JsonProperty("ID")
    private Integer id;
    @NotNull
    @JsonProperty("Name")
    private String name;
    @NotNull
    @JsonProperty("City")
    private String city;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof InsertQueryRequest)) return false;
        final InsertQueryRequest insertQueryRequest = (InsertQueryRequest) o;
        return Objects.equals(getId(), insertQueryRequest.getId()) &&
                Objects.equals(getName(), insertQueryRequest.getName()) &&
                Objects.equals(getCity(), insertQueryRequest.getCity());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getCity());
    }
}
