/*Copyright (c) 2017-2018 offline.com All Rights Reserved.
 This software is the confidential and proprietary information of offline.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with offline.com*/
package com.dev_6thjune_web.db123testing.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Time;
import java.util.Objects;

import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.wavemaker.commons.json.serializer.ByteArrayToStringSerializer;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Select1Response implements Serializable {

    @ColumnAlias("ID")
    private Integer id;
    @ColumnAlias("BYTE COL")
    private Byte byteCol;
    @ColumnAlias("SHORT COL")
    private Short shortCol;
    @ColumnAlias("INT COL")
    private Integer intCol;
    @ColumnAlias("LONG COL")
    private Long longCol;
    @ColumnAlias("FLOAT COL")
    private Double floatCol;
    @ColumnAlias("DOUBLE COL")
    private BigDecimal doubleCol;
    @ColumnAlias("BIGINT COL")
    private BigInteger bigintCol;
    @ColumnAlias("BIGDEC COL")
    private BigDecimal bigdecCol;
    @ColumnAlias("STRING COL")
    private String stringCol;
    @ColumnAlias("TEXT COL")
    private String textCol;
    @ColumnAlias("CLOB  COL")
    private String clobCol;
    @ColumnAlias("DATE_COL")
    private Date dateCol;
    @ColumnAlias("DATETIME COL")
    private LocalDateTime datetimeCol;
    @ColumnAlias("TIME COL")
    private Time timeCol;
    @ColumnAlias("TIMESTAMP COL")
    private LocalDateTime timestampCol;
    @ColumnAlias("BOOLEAN COL")
    private Boolean booleanCol;
    @JsonSerialize(using = ByteArrayToStringSerializer.class)
    @ColumnAlias("BLOB COL")
    private byte[] blobCol;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Byte getByteCol() {
        return this.byteCol;
    }

    public void setByteCol(Byte byteCol) {
        this.byteCol = byteCol;
    }

    public Short getShortCol() {
        return this.shortCol;
    }

    public void setShortCol(Short shortCol) {
        this.shortCol = shortCol;
    }

    public Integer getIntCol() {
        return this.intCol;
    }

    public void setIntCol(Integer intCol) {
        this.intCol = intCol;
    }

    public Long getLongCol() {
        return this.longCol;
    }

    public void setLongCol(Long longCol) {
        this.longCol = longCol;
    }

    public Double getFloatCol() {
        return this.floatCol;
    }

    public void setFloatCol(Double floatCol) {
        this.floatCol = floatCol;
    }

    public BigDecimal getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(BigDecimal doubleCol) {
        this.doubleCol = doubleCol;
    }

    public BigInteger getBigintCol() {
        return this.bigintCol;
    }

    public void setBigintCol(BigInteger bigintCol) {
        this.bigintCol = bigintCol;
    }

    public BigDecimal getBigdecCol() {
        return this.bigdecCol;
    }

    public void setBigdecCol(BigDecimal bigdecCol) {
        this.bigdecCol = bigdecCol;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public String getTextCol() {
        return this.textCol;
    }

    public void setTextCol(String textCol) {
        this.textCol = textCol;
    }

    public String getClobCol() {
        return this.clobCol;
    }

    public void setClobCol(String clobCol) {
        this.clobCol = clobCol;
    }

    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    public Time getTimeCol() {
        return this.timeCol;
    }

    public void setTimeCol(Time timeCol) {
        this.timeCol = timeCol;
    }

    public LocalDateTime getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(LocalDateTime timestampCol) {
        this.timestampCol = timestampCol;
    }

    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    public byte[] getBlobCol() {
        return this.blobCol;
    }

    public void setBlobCol(byte[] blobCol) {
        this.blobCol = blobCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Select1Response)) return false;
        final Select1Response select1response = (Select1Response) o;
        return Objects.equals(getId(), select1response.getId()) &&
                Objects.equals(getByteCol(), select1response.getByteCol()) &&
                Objects.equals(getShortCol(), select1response.getShortCol()) &&
                Objects.equals(getIntCol(), select1response.getIntCol()) &&
                Objects.equals(getLongCol(), select1response.getLongCol()) &&
                Objects.equals(getFloatCol(), select1response.getFloatCol()) &&
                Objects.equals(getDoubleCol(), select1response.getDoubleCol()) &&
                Objects.equals(getBigintCol(), select1response.getBigintCol()) &&
                Objects.equals(getBigdecCol(), select1response.getBigdecCol()) &&
                Objects.equals(getStringCol(), select1response.getStringCol()) &&
                Objects.equals(getTextCol(), select1response.getTextCol()) &&
                Objects.equals(getClobCol(), select1response.getClobCol()) &&
                Objects.equals(getDateCol(), select1response.getDateCol()) &&
                Objects.equals(getDatetimeCol(), select1response.getDatetimeCol()) &&
                Objects.equals(getTimeCol(), select1response.getTimeCol()) &&
                Objects.equals(getTimestampCol(), select1response.getTimestampCol()) &&
                Objects.equals(getBooleanCol(), select1response.getBooleanCol()) &&
                Objects.equals(getBlobCol(), select1response.getBlobCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getByteCol(),
                getShortCol(),
                getIntCol(),
                getLongCol(),
                getFloatCol(),
                getDoubleCol(),
                getBigintCol(),
                getBigdecCol(),
                getStringCol(),
                getTextCol(),
                getClobCol(),
                getDateCol(),
                getDatetimeCol(),
                getTimeCol(),
                getTimestampCol(),
                getBooleanCol(),
                getBlobCol());
    }
}
