/*Copyright (c) 2017-2018 offline.com All Rights Reserved.
 This software is the confidential and proprietary information of offline.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with offline.com*/

package com.dev_6thjune_web.db123testing.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.InputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.dev_6thjune_web.db123testing.AllTypes;
import com.dev_6thjune_web.db123testing.models.query.*;

public interface DB123TestingQueryExecutorService {

    Page<Select1Response> executeSelect1(Pageable pageable);

    InputStream getBlobColContentForSelect1(Integer id) throws EntityNotFoundException;

    Downloadable exportSelect1(ExportType exportType, Pageable pageable);

    Page<AllTypes> executeCdz(Pageable pageable);

    Downloadable exportCdz(ExportType exportType, Pageable pageable);

}


