/*Copyright (c) 2017-2018 offline.com All Rights Reserved.
 This software is the confidential and proprietary information of offline.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with offline.com*/

package com.dev_6thjune_web.test_blob1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.dev_6thjune_web.test_blob1.models.query.InsertQueryRequest;
import com.dev_6thjune_web.test_blob1.models.query.UpdateQueryRequest;

public interface Test_blob1QueryExecutorService {

    Integer executeUpdate_query(UpdateQueryRequest updateQueryRequest);

    Integer executeInsert_query(InsertQueryRequest insertQueryRequest);

}


